name: "Frontend: Publish NPM & Github Pages"

on:
  push:
    branches: ["v1"]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish to NPM & Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: valitydev/action-frontend/setup-install@v3
        with:
          release: true
          node-version: "lts/*"
          install: true
      - name: Bundle OpenAPI & Build Redocly Docs
        run: npm run build-web
      - name: Build Angular OpenAPI Library
        run: npm run build-ng-lib
      - name: Publish Angular OpenAPI Library
        uses: valitydev/action-frontend/publish@v3
        with:
          directory: ./lib
      - name: Publish Redocly Docs on Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web_deploy
