name: release
on:
  push:
    branches: [v0]
  workflow_dispatch:

env:
  NODEJS_VERSION: '16'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: npm
      - run: npm install
      - name: Bundle specification
        run: npm run build -- ../public
      - name: Deploy to release branch
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: release/v0
          folder: ../public/api
          target-folder: api
          commit-message: release ${{ github.repository }}@${{ github.sha }} by ${{ github.actor }}
